version: '3.1'

services:

  mysql:
    image: mysql/{{mysql_docker_meta[mysql_version]}}
    restart: always
    container_name: "mysql{{mysql_version}}"
    volumes:
      - /data/db/mysql{{mysql_version}}/data:/var/lib/mysql
      - /data/db/mysql{{mysql_version}}/my.cnf:/ect/my.cnf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: "{{mysql_root_password}}"
    ports:
      - {{mysql_port}}:3306

networks:
  default:
    external:
      name: "apps"